# -*- coding: utf-8 -*-
"""Day_2.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_GqAK_SbNjXOLhSpWaOjFNqlEl8A_xdA
"""

#List
a=[10,'Hello']

a[0] #List Indexing

a[1][0]

b=[20,'Python']

a+b

#Dictionary

price = {'a':10,'b':20} #Dictionary

price['a'] #Key to call

new_price ={'c':[100,200]}

print(price)

price.get('a')

#Sets

a={'a','b'}

b={'c','d'}

a.add('e')

print(a)

a.pop()

print(a)

#Tuple

a=(1,2,3,2,5,2,6,2)

a.count(2)

a.index(3)

b=(7,5,2)

c=a+b

print(c)

#String

a='Hello'

a.count('l')

a.index('e')

a[0]

b='World'

a+b

